# Generated by Django 3.1.5 on 2021-02-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HighlightRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_ranges', to='highlighter_api.video')),
            ],
            options={
                'unique_together': {('video', 'start', 'end')},
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.TextField(choices=[('UP', 'Upvote'), ('DOWN', 'Downvote')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('highlight_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlight_range_votes', to='highlighter_api.highlightrange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'highlight_range')},
            },
        ),
    ]
